# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/plasma-cascade-457105-h8/genai-assistant', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'genai-assistant',
           '--image', 'gcr.io/plasma-cascade-457105-h8/genai-assistant',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated',
           '--port', '8080']
images:
  - 'gcr.io/plasma-cascade-457105-h8/genai-assistant'